---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devqa-applications
  namespace: argocd
  labels:
    scope: system
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/Myafq/gitops-example-devqa-system.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}